### ISSUE TITLE
Create_MediaLive_Input.py input_sg error

### ISSUE THREAD

**Issue by jamesmalin** [aws-samples/aws-media-services-tools#4]
```python3 ./Create_MediaLive_Input.py```

Output:
Traceback (most recent call last):
  File "./Create_MediaLive_Input.py", line 180, in <module>
    input = rtmp_push(live, ID, input_sg(live))
  File "./Create_MediaLive_Input.py", line 159, in input_sg
    return response[0]['Id']
IndexError: list index out of range

**Comment by jamesmalin** [comment]
Temporarily fixed by commenting lines 157-160.

**Comment by LeahSiddall-aws** [comment]
i have merged this. thank you for catching the tpyo!

**Comment by jamesmalin** [comment]
@LeahSiddall-aws No problem! Also, this issue is more about lines 157-160. If you have no sg to list the script fails. So I commented out lines 157-160 to get it working. Not sure if you wanted to take a look at that.

Btw - thanks for putting this together! Saved some time.

**Comment by LeahSiddall-aws** [comment]
Ahh! That is why i was confused. I didn't realize these were two separate things. Let me dig into this for you.

**Comment by LeahSiddall-aws** [comment]
Looks like the exception case was looking for a dict key and not an array index. We didn't catch this because it only happens when there are 0 Security Group entries. I was able to replicate this in a region that I had no configured channels and find it was a [simple fix](https://github.com/aws-samples/aws-media-services-tools/commit/6f548962c7e3188d847afc53d5308ab84462ffdf). thanks for catching this, and hope this helps!
